/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointegrador;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;

/**
 * Ventana donde el usuario crea su cuenta. Le pedimos nombre, correo (o
 * numero, todavia no validamos cual de los dos es) y una contrasena, y
 * con eso llamamos a Autenticacion para guardar todo.
 *
 * @author CARLOS
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        personalizarEstilo();
        setLocationRelativeTo(null);
    }

    // ajustes de color y fuente que hicimos aparte del diseñador
    private void personalizarEstilo() {
        getContentPane().setBackground(Color.WHITE);

        lblTitulo.setForeground(new Color(43, 73, 224));
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 24));

        lblNombre.setFont(new Font("Segoe UI", Font.PLAIN,13));
        lblCorreo.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblContrasena.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        chkTerminos.setFont(new Font("Segoe UI", Font.PLAIN, 12));

        btnCrearCuenta.setBackground(new Color(61, 90, 241));
        btnCrearCuenta.setForeground(Color.WHITE);
        btnCrearCuenta.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnCrearCuenta.setFocusPainted(false);
        btnCrearCuenta.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblYaTienesCuenta.setForeground(new Color(90, 90, 90));
        lblYaTienesCuenta.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        chkTerminos = new javax.swing.JCheckBox();
        btnCrearCuenta = new javax.swing.JButton();
        lblYaTienesCuenta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrate");
        setResizable(false);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Registrate");

        lblNombre.setText("Nombre");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lblCorreo.setText("Correo o numero");

        lblContrasena.setText("Contrasena");

        chkTerminos.setText("Acepto los terminos y condiciones");

        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearCuentaMouseClicked(evt);
            }
        });

        lblYaTienesCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYaTienesCuenta.setText("¿Ya tienes cuenta? Inicia sesion");
        lblYaTienesCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblYaTienesCuentaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrasena)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTerminos)
                    .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYaTienesCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addContainerGap(60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitulo)
                .addGap(28, 28, 28)
                .addComponent(lblNombre)
                .addGap(6, 6, 6)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblCorreo)
                .addGap(6, 6, 6)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblContrasena)
                .addGap(6, 6, 6)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(chkTerminos)
                .addGap(28, 28, 28)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblYaTienesCuenta)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>                        

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO: no hace falta manejar el Enter aqui, se usa el boton
    }                                           

    private void btnCrearCuentaMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // recogemos los datos que el usuario lleno en el formulario
        String nombre = txtNombre.getText().trim();
        String correo =txtCorreo.getText().trim();
        String clave = new String(password.getPassword());

        if (nombre.isEmpty()|| correo.isEmpty() || clave.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor completa todos los campos.",
                    "Datos incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // validamos que haya marcado el checkbox de terminos, si no,
        // no dejamos seguir con la creacion de la cuenta
        if (!chkTerminos.isSelected()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debes aceptar los terminos y condiciones.",
                    "Terminos no aceptados",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        boolean creado =Autenticacion.registrarUsuario(nombre, correo, clave);

        if (!creado) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ya existe una cuenta registrada con ese correo.",
                    "Cuenta existente",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Cuenta creada correctamente.");
        // si todo salio bien, regresamos al login para que inicie sesion
        new IniciarSesion().setVisible(true);
        this.dispose();
    }                                           

    private void lblYaTienesCuentaMouseClicked(java.awt.event.MouseEvent evt) {                                               
        new IniciarSesion().setVisible(true);
        this.dispose();
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // declaracion variables                    
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JCheckBox chkTerminos;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblYaTienesCuenta;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
                
}
