/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointegrador;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;

/**
 * Ventana donde el usuario pone la contrasena nueva, despues de haber
 * confirmado en OlvidasteContrasena que su cuenta si existe.
 *
 * @author CARLOS
 */
public class CambiarContrasena extends javax.swing.JFrame {

    /**
     * Correo del usuario que nos llega desde la pantalla anterior
     * (OlvidasteContrasena). Esta variable no la genera el Form Editor,
     * la agregamos nosotros a mano para saber a que cuenta hay que
     * actualizarle la contrasena.
     */
    private final String correoUsuario;

    /**
     * Creates new form CambiarContrasena
     */
    public CambiarContrasena() {
        this(null);
    }

    public CambiarContrasena(String correoUsuario) {
        this.correoUsuario = correoUsuario;
        initComponents();
        personalizarEstilo();
        setLocationRelativeTo(null);
    }

    private void personalizarEstilo() {
        getContentPane().setBackground(Color.WHITE);

        lblTitulo.setForeground(new Color(43, 73, 224));
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 22));

        lblContrasena.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        lblConfirmarContrasena.setFont(new Font("Segoe UI", Font.PLAIN,13));

        btnCambiar.setBackground(new Color(61, 90, 241));
        btnCambiar.setForeground(Color.WHITE);
        btnCambiar.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnCambiar.setFocusPainted(false);
        btnCambiar.setCursor(new Cursor(Cursor.HAND_CURSOR));

        btnAtras.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblContrasena = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        lblConfirmarContrasena = new javax.swing.JLabel();
        passwordConfirmar = new javax.swing.JPasswordField();
        btnCambiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambia tu contrasena");
        setResizable(false);

        btnAtras.setText("<-");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cambia tu contrasena");

        lblContrasena.setText("Nueva contrasena");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        lblConfirmarContrasena.setText("Confirmar contrasena");

        passwordConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordConfirmarActionPerformed(evt);
            }
        });

        btnCambiar.setText("Cambiar contrasena");
        btnCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblContrasena)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmarContrasena)
                    .addComponent(passwordConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAtras)
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(32, 32, 32)
                .addComponent(lblContrasena)
                .addGap(6, 6, 6)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblConfirmarContrasena)
                .addGap(6, 6, 6)
                .addComponent(passwordConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>                        

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {                                       
        new OlvidasteContrasena().setVisible(true);
        this.dispose();
    }                                      

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO: no lo necesitamos, el cambio se hace con el boton
    }                                        

    private void passwordConfirmarActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO: igual que arriba, no hace falta manejar el Enter aqui
    }                                               

    private void btnCambiarMouseClicked(java.awt.event.MouseEvent evt) {                                        
        String clave = new String(password.getPassword());
        String confirmar =new String(passwordConfirmar.getPassword());

        if (clave.isEmpty() || confirmar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Completa ambos campos de contraseña.",
                    "Datos incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // revisamos que las dos contrasenas escritas sean iguales antes
        // de mandar a guardar cualquier cosa
        if(!clave.equals(confirmar)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Las contraseñas no coinciden.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (correoUsuario == null || !Autenticacion.actualizarContrasena(correoUsuario, clave)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No se pudo actualizar la contraseña.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this, "Contraseña actualizada correctamente.");
        new IniciarSesion().setVisible(true);
        this.dispose();
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarContrasena(null).setVisible(true);
            }
        });
    }

    // declaracion variables                   
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JLabel lblConfirmarContrasena;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField passwordConfirmar;
                
}
