/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectointegrador;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;

/**
 * Ventana que aparece cuando el usuario dice que olvido su contrasena.
 * Aqui solo le pedimos su correo (o numero) para verificar que la cuenta
 * exista, y si existe lo mandamos a la pantalla donde puede poner una
 * contrasena nueva.
 *
 * @author CARLOS
 */
public class OlvidasteContrasena extends javax.swing.JFrame {

    /**
     * Creates new form OlvidasteContrasena
     */
    public OlvidasteContrasena() {
        initComponents();
        personalizarEstilo();
        setLocationRelativeTo(null);
    }

    private void personalizarEstilo() {
        getContentPane().setBackground(Color.WHITE);

        lblTitulo.setForeground(new Color(43, 73, 224));
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD,22));

        lblUsuario.setFont(new Font("Segoe UI", Font.PLAIN, 13));

        btnContinuar.setBackground(new Color(61, 90, 241));
        btnContinuar.setForeground(Color.WHITE);
        btnContinuar.setFont(new Font("Segoe UI", Font.BOLD, 13));
        btnContinuar.setFocusPainted(false);
        btnContinuar.setCursor(new Cursor(Cursor.HAND_CURSOR));

        btnAtras.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Olvidaste tu contrasena");
        setResizable(false);

        btnAtras.setText("<-");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Olvidaste tu contrasena");

        lblUsuario.setText("Correo o numero telefonico");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnContinuar.setText("Continuar");
        btnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinuarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnAtras)
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addGap(36, 36, 36)
                .addComponent(lblUsuario)
                .addGap(6, 6, 6)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>                        

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // el usuario se arrepintio, lo regresamos al login
        new IniciarSesion().setVisible(true);
        this.dispose();
    }                                      

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO: no lo manejamos aqui, el flujo sigue con el boton Continuar
    }                                          

    private void btnContinuarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        String usuario = txtUsuario.getText().trim();
        if(usuario.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingresa tu correo o numero telefonico.",
                    "Dato requerido",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // antes de mandarlo a cambiar la contrasena, nos aseguramos de
        // que en verdad exista una cuenta con ese dato
        if (!Autenticacion.existeUsuario(usuario)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No existe una cuenta registrada con ese dato.",
                    "Usuario no encontrado",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        new CambiarContrasena(usuario).setVisible(true);
        this.dispose();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlvidasteContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlvidasteContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlvidasteContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlvidasteContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlvidasteContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration                   
}
